### ISSUE TITLE
Function-Level Vulnerability Detection Support in ReposVul Dataset

### ISSUE THREAD

**Issue by Ffffffffire** [PILOT-VD-2023/ReposVul#2]
Dear Authors,

Thanks for your efforts in conducting this significant research work. Your contributions are invaluable to advancing the field of vulnerability detection research.

I plan to undertake research on function-level vulnerability detection using the ReposVul dataset. However, I have encountered some challenges in trying to utilize the ReposVul dataset, specifically unclear on how to accurately extract function-level code snippets and their corresponding CVE and other relevant information from the provided data. Could you please offer some guidance or additional information on how to identify and extract individual function-level code snippets and other related information such as CVE details from the dataset. Thank you for taking the time to read my request. Looking forward to your reply!

**Comment by Eshe0922** [comment]
Thank you for your interest in our work. We have displayed the data column names in Data Description.

**Comment by bigpinwheel666** [comment]
Dear Authors,

Thanks for your efforts in conducting this significant research work.I would like to know what the values of -1,0,1 are for each target file in details. and which condition they correspond .  looking forward to hearing from you

**Comment by Eshe0922** [comment]
Thank you for your attention. 1 indicates that both LLM and static tools believe that the code snippet has vulnerabilities, while 0 indicates the opposite. When it is -1, there is a contradiction between the judgment results of LLM and static tools.
