### ISSUE TITLE
Maybe a wrong in code

### ISSUE THREAD

**Issue by shuoshu131** [PILOT-VD-2023/ReposVul#3]
Dear Authors,
Thanks for your efforts in conducting this significant research work. Your contributions are invaluable to advancing the field of vulnerability detection research.
This day, when I view the code in vscode, I find a warning line in Path:Vulnerability_Untangling_Module\llm\llm_evaluate.py Line:250

```
if detail['agree_check'] = -1 and detail['file_language'] in language:
```

I thought it is not "=" but "==".
If this is exactly a wrong hope this issue can help you, else   i'm sorry to make this issue recklessly

**Comment by Eshe0922** [comment]
Thank you for your suggestion. This is indeed a code error, but we discovered it during the construction process of our final dataset.
