### ISSUE TITLE
How to construct the data at CWE.csv?

### ISSUE THREAD

**Issue by ybdesire** [PILOT-VD-2023/ReposVul#4]
Thanks for the great work.  :)
Would you share how did you construct the data at `Vulnerability_Untangling_Module/llm/CWE.csv`?

**Comment by Eshe0922** [comment]
Thank you for your question. We obtained the latest CWE.csv from the CWE official website.

**Comment by ybdesire** [comment]
Got that. Thanks @Eshe0922  for the update.
